/*
 ### jQuery Codepress Plugin v1.2 - 2008-02-20 ### * https://www.fyneworks.com/ - diego@fyneworks.com
Licensed under a Creative Commons Attribution-Share Alike 2.0 UK: England & Wales License
	-	LICENSE INFO:
	  http://creativecommons.org/licenses/by-sa/2.0/uk/
	-	CREDIT LINK (at your convenience):
	  <a rel="license" href="http://creativecommons.org/licenses/by-sa/2.0/uk/"><img alt="Creative Commons License" style="border-width:0" src="http://i.creativecommons.org/l/by-sa/2.0/uk/88x31.png"/></a><br/><span xmlns:dc="http://purl.org/dc/elements/1.1/" href="http://purl.org/dc/dcmitype/Text" property="dc:title" rel="dc:type">jQuery Codepress Plugin</span> by <a xmlns:cc="http://creativecommons.org/ns#" href="https://www.fyneworks.com/" property="cc:attributionName" rel="cc:attributionURL">Fyneworks.com</a> is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-sa/2.0/uk/">Creative Commons Attribution-Share Alike 2.0 UK: England & Wales License</a>.
	###
 Project: https://github.com/fyneworks/codepress
 Website: https://codepress.fyneworks.com/
*/
eval(function(p,a,c,k,e,r){e=function(c){return(c<a?'':e(parseInt(c/a)))+((c=c%a)>35?String.fromCharCode(c+29):c.toString(36))};if(!''.replace(/^/,String)){while(c--)r[e(c)]=k[c]||e(c);k=[function(e){return r[e]}];e=function(){return'\\w+'};c=1};while(c--)if(k[c])p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c]);return p}(';5(D.u)(3($){$.7($,{2:{v:{},6:\'/2/\',c:[],f:w,h:E,F:3(i){15{8 i.2.x.16()}17(e){8\'\'}},j:3(){4 e=$.2.c;18(4 i=0;i<e.d;i++){4 a=e[i].k;4 T=$(e[i]);4 b=$.2.F(e[i]);T.G(b).H(b).I(\'J\',w);5(b!=a.H())K(\'19 L 1a M N:\'+\'\\n\'+\'1b 1c j O P\')}},Q:3(a){4 o=$.7({},$.2.v||{},a||{});$.7(o,{y:(o.y||\'k.1d, k.2\'),6:(o.6||$.2.6||\'\')});4 e=$(o.e);5(!e.d>0)e=$(o.y);5(!e.d>0)8;o=$.7({},o,($.1e?e.P():($.R?e.R():E))||{});5(!$.2.S&&!$.2.f){$.2.S=U;$.1f(o.6+\'2.1g\',3(){$.2.f=U})};4 b=3(e){5($.2.f){$.2.x(e,o)}V{5($.2.1h<=0){K(\'u.2 N L: 1i M 1j 1k 1l 1m.\')}V{$.2.1n--;D.1o(b,1p,e)}}};b(e);8 e},W:3(){5($.2.h)8;$.2.h={l:$.z.l||3(){}};$.z.l=3(){$.2.j();8 $.2.h.l.1q(X,1r)};$(\'O\').1s(3(){$.2.j()})},x:3(e,o){o=$.7($.2.v||{},o||{});$.7(o,{m:(o.m||o.1t||\'1u%\'),p:(o.p||o.1v||\'1w\'),6:(o.6||$.2.6)});e=$(e);5(e.1x()>0){4 a=($.2.c||[]);e.1y(3(i,t){4 T=$(t);t.A=(t.A||\'2\'+($.2.c.d+1));5(t.A&&!t.2){4 n=a.d;T.1z().p(o.p).m(o.m);4 b=1A(t.Y),9=\'\';9+=\' 2\';9+=(\' Z-\'+(!b.q(/Z/g)?\'B\':\'C\'));9+=(\' 10-\'+(b.q(/10/g)?\'B\':\'C\'));9+=(\' 11-\'+(b.q(/11/g)?\'B\':\'C\'));9+=\' \'+(b.q(/12|1B|1C|1D|1E|1F|1G|1H|G/13)||[\'12\'])[0];t.Y=9.1I(/(^\\s+)|(\\s+$)/13,\'\');r.1J=r.1K();r.6=o.6;t.2=1L r(t);T.I(\'J\',w).1M().1N(t.2);a[n]=t;a[n].k=T}});$.2.c=a};8 e},14:3(o){$.2.W();8 $.2.Q(o)}}});$.7($.z,{2:3(o){$.2.14($.7(o||{},{e:X}))}})})(u);',62,112,'||codepress|function|var|if|path|extend|return|c2|||list|length||loaded||intercepted||update|textarea|ajaxSubmit|width|||height|match|CodePress|||jQuery|config|false|editor|selector|fn|id|on|off|window|null|content|text|val|attr|disabled|alert|error|Codepress|plugin|form|data|create|metadata|loading||true|else|intercept|this|className|linenumbers|autocomplete|readonly|html|gi|start|try|getCode|catch|for|Critical|in|Unable|to|code|meta|getScript|js|waited|The|script|did|not|load|waitFor|setTimeout|1000|apply|arguments|submit|Width|100|Height|500px|size|each|show|String|css|php|java|javascript|perl|ruby|sql|replace|engine|getEngine|new|parent|prepend'.split('|'),0,{}))